"sudo yum install mariadb-server"
"sudo systemctl enable mariadb"
"sudo systemctl start mariadb"
"mysqladmin -u root password '${var.database_pass}'"
"mysql -u root -p"
"CREATE USER 'wordpress-user'@'${aws_instance.wordpress_instance.private_ip}' IDENTIFIED BY '${var.database_pass}';"
"CREATE DATABASE `wordpress-db`;"
"GRANT ALL PRIVILEGES ON `wordpress-db`.* TO "wordpress-user"@"${aws_instance.wordpress_instance.private_ip}";"
"FLUSH PRIVILEGES;"