"wget https://wordpress.org/latest.tar.gz"
"tar -xzf latest.tar.gz"
"cp wordpress/wp-config-sample.php wordpress/wp-config.php"
"sed -i 's/database_name_here/wordpress-db/' wordpress/wp-config.php"
"sed -i 's/username_here/${var.database_user}/' wordpress/wp-config.php"
"sed -i 's/password_here/${var.database_pass}/' wordpress/wp-config.php"
"sudo yum install httpd"
"sudo systemctl enable httpd"
"sudo systemctl start httpd"
"sudo amazon-linux-extras | grep php" 
"sudo amazon-linux-extras enable php8.1 sudo yum clean metadata"
"sudo yum install php"
"sudo yum install php- {pear,cgi,common,curl,mbstring,gd,mysqlnd,gettext,bcmath,json,xml,fp m,intl,zip,imap}"
"sudo chown -R apache:apache /var/www/html/wordpress"
"sudo cp -r wordpress/* /var/www/html/"
"sudo systemctl restart httpd"
"sudo systemctl start httpd"